Repository gem/oq-irmt-qgis, pull requests merged in 2018-02, with the labels that each got.

#377 Fixed retrieval of the engine server hostname from settings
  svir/dialogs/standalone_app_dialog.py
  svir/metadata.txt
Labels: bug, high priority

#379 Remove menu items to load hmaps hcurves and uhs from npz
  svir/irmt.py
Labels: bug

#385 Companion of https://github.com/gem/oq-engine/pull/3446
  svir/dialogs/load_hmaps_as_layer_dialog.py
Labels: enhancement

#391 Enable loading hmaps corresponding to all IMTs and PoEs
  svir/dialogs/load_hmaps_as_layer_dialog.py
  svir/metadata.txt
Labels: bug
