Repository gem/oq-irmt-qgis, pull requests merged in 2019-03, with the labels that each got.

#541 Show traceback
  svir/calculations/calculate_utils.py
  svir/dialogs/download_layer_dialog.py
  svir/dialogs/drive_oq_engine_server_dialog.py
  svir/dialogs/load_basic_csv_as_layer_dialog.py
  svir/dialogs/load_hmaps_as_layer_dialog.py
  svir/dialogs/load_output_as_layer_dialog.py
  svir/dialogs/load_ruptures_as_layer_dialog.py
  svir/dialogs/projects_manager_dialog.py
  svir/dialogs/recovery_settings_dialog.py
  svir/dialogs/settings_dialog.py
  svir/dialogs/transformation_dialog.py
  svir/dialogs/upload_dialog.py
  svir/dialogs/upload_settings_dialog.py
  svir/dialogs/viewer_dock.py
  svir/dialogs/weight_data_dialog.py
  svir/irmt.py
  svir/metadata.txt
  svir/utilities/utils.py
Labels: enhancement

#540 Let integration tests reuse more code from the plugin instead of reimplementing parts of it
  svir/dialogs/drive_oq_engine_server_dialog.py
  svir/test/integration/test_drive_oq_engine.py
Labels: enhancement, internal

#543 Fixed the management of realizations
  svir/dialogs/load_gmf_data_as_layer_dialog.py
  svir/dialogs/viewer_dock.py
  svir/metadata.txt
  svir/test/integration/test_drive_oq_engine.py
Labels: internal
